### ISSUE TITLE
Add note button

### ISSUE THREAD

**Issue by FTno** [sunilpaulmathew/sNotz#12]
Scrolling down the list of notes I find the add note button somewhat disturbing laying on top of notes.
Maybe placing it in the toolbar is a better solution?

**Comment by sunilpaulmathew** [comment]
@FTno 
I think, integrating that button to the top toolbar will make it bit crowded (since 3 buttons were already there). I really want it to be more independent from others. Probably reserve a dedicated space at the bottom along with a text (Create Note or Add Note)? Please see the screenshot from one of my other app.
![Screenshot_1635966397](https://user-images.githubusercontent.com/15515387/140176432-f3d58665-2a2e-4d3a-ae02-b4332757343d.png)

**Comment by Lennoard** [comment]
A FAB can hide itself if attached to a scrolling `RecyclerView`. I think that will be best.

**Comment by sunilpaulmathew** [comment]
> 
> 
> A FAB can hide itself if attached to a scrolling `RecyclerView`. I think that will be best.

Yup, That will be the perfect way. Thanks for idea.

**Comment by sunilpaulmathew** [comment]
@Lennoard  @FTno 
Don't know this is the ideal way, but the **Add** button will be hidden when the _RecyclerView_ is on scrolling. Please checkout the video linked below.
https://user-images.githubusercontent.com/15515387/140291292-109ede09-422b-4b36-8ce4-ca467226b7b4.mp4

**Comment by Lennoard** [comment]
> @Lennoard @FTno Don't know this is the ideal way, but the **Add** button will be hidden when the _RecyclerView_ is on scrolling. Please checkout the video linked below. https://user-images.githubusercontent.com/15515387/140291292-109ede09-422b-4b36-8ce4-ca467226b7b4.mp4

Yes. Just missing the hide scale animation.

**Comment by Lennoard** [comment]
> > A FAB can hide itself if attached to a scrolling `RecyclerView`. I think that will be best.
> 
> Yup, That will be the perfect way. Thanks for idea. Edit: Btw, its not a FAB, its an ImageButtom inside a CardView.

Any particular reason?

**Comment by sunilpaulmathew** [comment]
> 
> 
> > > A FAB can hide itself if attached to a scrolling `RecyclerView`. I think that will be best.
> > 
> > 
> > Yup, That will be the perfect way. Thanks for idea. Edit: Btw, its not a FAB, its an ImageButtom inside a CardView.
> 
> Any particular reason?

Don't know, but somehow I don't like using FAB's. I prefer using MaterialCardView with a Text & Icon instead (Ofcousrse, not text in the case of sNotz).

**Comment by FTno** [comment]
Nice feature when scrolling, but when you expand a note wouldn't the button still be on top of the note and disturb reading so you have to scroll to have a clear view (especially in the bottom part).

**Comment by sunilpaulmathew** [comment]
> 
> 
> Nice feature when scrolling, but when you expand a note wouldn't the button still be on top of the note and disturb reading so you have to scroll to have a clear view (especially in the bottom part).

Probably a bit disturbing. However, when you read longer notes, you will have to scroll it anyway (which will hide the button).
