### ISSUE TITLE
In-note colour selector displays wrong colour

### ISSUE THREAD

**Issue by uli-on** [sunilpaulmathew/sNotz#13]
The in-note colour selector for the text colour comes up with the colour of the background set in the prefs. It correctly changes the text colour, though.

Edit: Similar is valid for in-note background colour picker, it always opens with the prefs value applied. 

sNotz v0.19

**Comment by sunilpaulmathew** [comment]
Thanks @uli-on 
I noticed it a couple of times. But always busy with other parts of app and eventually forget it. Will fix it soon.

**Comment by uli-on** [comment]
> Closed #13 <https://github.com/sunilpaulmathew/sNotz/issues/13> via a93e463 <https://github.com/sunilpaulmathew/sNotz/commit/a93e4633e8f92f8c0e2961a8b05f000a007d658a>.
> 

Thanks!
