### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by FTno** [sunilpaulmathew/sNotz#14]
When you have selected 'Date Created' notes you modify goes to the top, so I think 'Date modified' will be more appropriate to use here (and this will also be more in line with other apps). My interpretation of 'Date Created' is that it then should be sorted by the initial creation date of notes.

**Comment by sunilpaulmathew** [comment]
@FTno 
You're right. sNotz already started overwriting the date created on each update. I agree that **Date modified** will make more sense. Will update app accordingly. Btw, if you're not aware, here is a small website for [sNotz](https://sunilpaulmathew.github.io/sNotz/).

**Comment by FTno** [comment]
Nice website for sNotz, you should add a link to it from F-Droid.

**Comment by sunilpaulmathew** [comment]
> te for sNotz, you should add a link to

Thanks. I'm feeling too lazy to make another MR for that. But, will do that sometimes in future.
