### ISSUE TITLE
Suggestion: Text export and import be QR code

### ISSUE THREAD

**Issue by mofosyne** [sunilpaulmathew/sNotz#17]
Would be handy to share text between phones.

**Comment by sunilpaulmathew** [comment]
@mofosyne 
I don't understand. Are you talking about backup/restore?

**Comment by Lennoard** [comment]
Keep in mind that QR codes have a max possible length of ~4Kb, that's ~4000 characters.

**Comment by sunilpaulmathew** [comment]
> Keep in mind that QR codes have a max possible length of ~4Kb, that's ~4000 characters.

Plus + an additional permissions (camera and?) which may not be okay for all users.

**Comment by mofosyne** [comment]
Possible use case for QR camera support:
* Quickly adding URLs from QR codes that you see in the field
* Copying text from computer (if there is a way to display copy/paste as QR code)

Possible use case for displaying text notes in QR format:
* Quick sharing of textual content from one phone to another
* Quick sharing of url if we share just the url

And yes there is a limitation of 4Kb. 

But could be worked around if text is split across multiple QR code, however this would have to be specific to this app as you need to agree to some form of encoding of chunk number. So in practice this is most likely just for sharing smaller text notes.

If you want to do split QR codes, it can perhaps be for backing up notes into paper or something for longer term storage.

**Comment by sunilpaulmathew** [comment]
@mofosyne 
Thanks for elaborating the issue. Definitely interesting. I'll seriously think about acquiring simple notes from QR codes and vice versa (share simple notes after converting into QR code) . I'm adding an enhancement tag to this issue now. For implementation, more research is needed (so, probably more time).

**Comment by sunilpaulmathew** [comment]
@mofosyne 
Sorry for the slight delay. I finally made some efforts to address this issue (still very basic). If you like to have some testing, [here is a test build for you](https://www.dropbox.com/s/uzbj39b6hbdtj5p/com.sunilpaulmathew.snotz.apk?dl=0). I may not include this in the immediate next version (hopefully submit in few hours). So, please take your time for testing. & finally, suggestions are most welcome. Thanks
![Screenshot_1637617801](https://user-images.githubusercontent.com/15515387/142941587-00d2e8bd-952a-406f-a44b-ba5c0c83ee46.png)
![Screenshot_1637617808](https://user-images.githubusercontent.com/15515387/142941589-c8184646-2e86-42d7-8329-98e2228f999e.png)

**Comment by mofosyne** [comment]
That's pretty quick.

So far what I noticed

* QR code reading a new note makes sense -- PASS
* QR code reading from images didn't quite work (Photos from my phone, when I take photos of random QR codes I see) -- FAIL
* QR code image generation via pressing the "share icon" then "Share as QR code" works -- PASS
    - But it slapped on this text `Get sNotz v0.21, a simple, yet much useful application to manage notes, from PlayStore: https://play.google.com/store/apps/details?id=com.sunilpaulmathew.snotz` which can be misleading. It should at least provide a short snippet preview of the QR code text content, then provide an ad to your app.

Stuff I tried to do, but cannot do yet. So is possible UX bug.

* QR code image generation via just immediately showing a QR code on screen
* Add more text to existing notes via QR code

Hmmmm... also some other UX consideration

* What if one side of sliding is not to delete a note, but to quickly open a note in read only mode?
* What if during the read only mode window, there is a button for quickly switching the display to QR code?

Anyway hope that gives you some ideas

**Comment by sunilpaulmathew** [comment]
Thanks a lot for the testing and feedbacks (& also for new idea).

> * QR code reading from images didn't quite work

I don't think it work if you try to scan an image with QR code and other data. But, it should work if the image contains only QR data. I really don't have a better method to improve it atm. 

> *  But it slapped on this text `Get sNotz v0.21, a simple, yet much useful application to manage notes, from PlayStore: https://play.google.com/store/apps/details?id=com.sunilpaulmathew.snotz` which can be misleading. It should at least provide a short snippet preview of the QR code text content, then provide an ad to your app.

Okay, it was my mistake, I forgot to remove the EXTRA_TEXT from intent. Btw, what do you mean by the _short snippet preview_. I thought it will be fine to just share the image alone.

> * Not sure what's the purpose of this feature of sending QR code images of the text content.

I'm also bit confused about how useful it is. Probably, replace that option with _Generate QR code_, which will show the newly generated image, and let the user to decide share, save or discard?

Regarding the new suggestions:

> * Add more text to existing notes via QR code

It's a good one, but I have to consider (in-fact, learn) more things to do it.

> * What if one side of sliding is not to delete a note, but to quickly open a note in read only mode?

Also a good idea. Alternatively, how about adding a new menu on long clicking a note (see attached photo, which I'm currently testing). We can include new stuff (such as read-mode) there as well.

![Screenshot_20211123-152401_1](https://user-images.githubusercontent.com/15515387/143042022-594a1fdc-4c70-433b-9675-acae0237bb9b.jpg)

> * What if during the read only mode window, there is a button for quickly switching the display to QR code?

It will be super easy. Also, may be, a similar option in normal create/edit text mode?

Once again, thanks a lot!

**Comment by sunilpaulmathew** [comment]
@mofosyne 
Can you test the new version, please. It is available [here](https://www.dropbox.com/s/uzbj39b6hbdtj5p/com.sunilpaulmathew.snotz.apk?dl=0). Not all the suggestions are addressed. But, it should be hopefully, much better.
Thanks a lot in advance.

**Comment by mofosyne** [comment]
Nice. The button to render the notes as QR code directly to screen works well.

Also the share QR code comes out of telegram like below:

![Screenshot_20211124-180045.png](https://user-images.githubusercontent.com/827793/143190340-ea607d0b-8955-4027-865b-ae61182f4cad.png)

As for why show a small preview of the QR content when sharing. It makes it easier to find a particular QR code if you have multiple images to look though.

**Comment by sunilpaulmathew** [comment]
@mofosyne 
Thanks for the feedback, again.
& regarding the preview, I might append first few words (probably 2 or 3) of the note with the message. Don't know it is possible to add it to the image itself.

**Comment by mofosyne** [comment]
That's the idea. Of course if you can add it to the image, that would make it more portable. For simplicity sake I would just get the first 25 characters then append a `...` if there is more than 25 characters in the message. Otherwise you would need to parse the content into words. e.g. `Cat purchase note ...`

**Comment by mofosyne** [comment]
Btw thanks for getting the QR code thing going. Just wondering how the QR code thing is going for you.

Have you tried one of those QR desktop scanners? This means you can easily transfer notes from phone to the PC, might be something to note in the tips and tricks.

![image](https://github.com/sunilpaulmathew/sNotz/assets/827793/f0be85cb-86ac-4726-aa6b-bfab952160bc)
