### ISSUE TITLE
Random colors

### ISSUE THREAD

**Issue by trustable-code** [sunilpaulmathew/sNotz#23]
I would enjoy an opt-in feature, which sets a random color for each note and hides the color picker when editing a note.

Edit: With "random color" I mean a color choosen from a set of suitable colors, not complety random, which would not look good.

**Comment by sunilpaulmathew** [comment]
@trustable-code 
Thanks a lot for this idea. Although it is a really good suggestion, it need some serious work and testing. Still, don't know how good it work. I'm adding an _enhancement_ label with this issue.

**Comment by trustable-code** [comment]
I have just tested it, works very nice, thank you :)
