### ISSUE TITLE
Checklists

### ISSUE THREAD

**Issue by mohananpg** [sunilpaulmathew/sNotz#25]
Hi. I was testing it. I could not find out how to delete a checklist. Also, it would be nice if the cursor positions in the next available item slot after pressing enter. I used it in Android 11 on an asus rog 5 Ultimate. V 0.24
Overall, it is a nice software. 
Best regards
Mohanan PG

**Comment by sunilpaulmathew** [comment]
Hi @mohananpg 
Thanks for the comment and sorry for the slight delay in my response.
You can simply delete a check list by swiping right or left (and confirm delete). Regarding the second comment, I have to look on it (don't know how to do it at this moment). I'm adding an "enhancement" and "help wanted" labels to this issue.
Regards
Sunil

**Comment by mohananpg** [comment]
Dear Sunil
Thank you very much.
I shall try it.
You've created some wonderful tools indeed.
Congratulations.
Best regards
MohananPG
