### ISSUE TITLE
Auto save on forced close of the app

### ISSUE THREAD

**Issue by trustable-code** [sunilpaulmathew/sNotz#27]
Feature request:
When the app is closed, it should automatically save the note.
Currently the changes of a note a lost, when the app is left in editing mode and then quit by the system.
Other notes apps have this functionality.

**Comment by sunilpaulmathew** [comment]
@trustable-code 
Have you tried the "Auto Save Notes" option in settings. It will save notes upon leaving the edit page (though, changes will be discarded if you forced close the app). Please let me know you're looking for something else.
Regards,
Sunil

**Comment by trustable-code** [comment]
@sunilpaulmathew
Yes, I have "Auto Save Notes" enabled. The way the app is closed is by swiping the window away in the Android window overview.

**Comment by Lennoard** [comment]
@sunilpaulmathew you should **silently** save the note every time `onStop()` is called if the autosave preference is enabled.

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew Yes, I have "Auto Save Notes" enabled. The way the app is closed is by swiping the window away in the Android window overview.

That's what I mean by forced close.

> @sunilpaulmathew you should **silently** save the note every time `onStop()` is called if the autosave preference is enabled.

Thanks. It is definitely possible. However,  I seriously doubt it will slow (or even freeze) down the app if number of already existing notes are high. Still, nothing wrong to try. Adding an "enhancement" label now.

**Comment by Lennoard** [comment]
> However, I seriously doubt it will slow (or even freeze) down the app if number of already existing notes are high

This shouldn't be a problem, you'll be saving just one note alone. Also, you can use a separate thread.

**Comment by sunilpaulmathew** [comment]
@trustable-code @Lennoard 
Let us see the pushed commit will solve this issue or not.
