### ISSUE TITLE
Solid background on checklists widget

### ISSUE THREAD

**Issue by jj-sallo** [sunilpaulmathew/sNotz#28]
As seen below, text on the checklists widget can be hard to read with a transparent background. Please make the background color solid, or make background transparency configurable.

![Screenshot_20220311-154241_1.png](https://user-images.githubusercontent.com/60981826/157975460-044d1119-3908-4cab-bfd8-2f536ae88ef7.png)

**Comment by sunilpaulmathew** [comment]
@jj-sallo 
Or the text (& checkbox) color configurable. I personally feel transparent background is more beautiful.
Thanks for raising this issue, btw

**Comment by jj-sallo** [comment]
More options are always welcome, the main issue being readability. Thanks for the fast response!

**Comment by sunilpaulmathew** [comment]
> More options are always welcome, the main issue being readability. Thanks for the fast response!

In v0.25, I added an option to change checklist widget color (please check settings page). I hope it will address this issue. If not, feel free to reopen this issue.
