### ISSUE TITLE
cannot find data files

### ISSUE THREAD

**Issue by CrawfordRD** [sunilpaulmathew/sNotz#31]
I recently installed sNotz on my Galaxy S21. According to the description for sNotz at the Google Play Store, "ll the notes are stored locally in "json" format within the files directory (/data/data/com.sunilpaulmathew.snotz/files/) of sNotz. However, on my Android 12 cell phone there is no /data directory, even when I turn the "Show hidden files" option on. The closest thing I found to it was "/Android/data/", which contained a bunch of com.* subdirectories, but none with the string "snotz" or "sunilpaulmatthew.snotz" in their filenames. Could you please tell me what the correct path to the data files for sNotz is on my Android phone?

Thank you in advance.

**Comment by sunilpaulmathew** [comment]
I don't know if I wrote incorrectly. The correct path is /sdcard/Android/data/com.sunilpaulmathew.snotz/files/

**Comment by CrawfordRD** [comment]
Thank you for the VERY QUICK reply! It was very helpful.
