### ISSUE TITLE
Feature request: duplicate/copy a note

### ISSUE THREAD

**Issue by nobrowser** [sunilpaulmathew/sNotz#35]
I'd like to have a way to create an exact copy of the note being edited. If the text needs to be unique for implementation reasons, just append some trivial bit to it. Example: I have a note "Get a haircut"; with this feature, I'd open it and one of the buttons on the top would just create "Copy of Get a haircut" or "Get a haircut *" or something like that.

This would be useful for 2 related reasons: to easily create "subtasks" that are somehow tied to the exisiting task (for example, I may edit the above to "Get a haircut - wash my hair first"), and also to create items of the exact same color, which is kind of difficult right now (there is no way to copy the color, that I know of).

Thanks. Btw, I just donated via paypal :-)

**Comment by sunilpaulmathew** [comment]
@nobrowser 
Firstly, thanks for the donation.

& are you talking about a kind of "**Duplicate Note**" feature? If so, I will try to do it in a future release.

**Comment by nobrowser** [comment]
> @nobrowser Firstly, thanks for the donation.
> 
> & are you talking about a kind of "**Duplicate Note**" feature? If so, I will try to do it in a future release.

Yes, "Duplicate Note" is one way to describe what I'd like to have. Thanks again for your work.


--
Ian
