### ISSUE TITLE
[SUGGESTION] Display checklist and notes together

### ISSUE THREAD

**Issue by HarriBuh** [sunilpaulmathew/sNotz#36]
As the title says. It's rather uncomfortable to switch from the "notes" hub to the "checklist" everytime, again and again.
Most of other note apps have this function as standard and I like it very much.

**Comment by sunilpaulmathew** [comment]
@HarriBuh 
You mean, display both in a same window, or two windows in the main screen that are easily reachable (e.g., by sliding)?

**Comment by HarriBuh** [comment]
@sunilpaulmathew yes, both in the same window. The app "Notally" on Fdroid uses this design, in case you were wondering how it should look.

**Comment by HarriBuh** [comment]
Any news on my request?

**Comment by sunilpaulmathew** [comment]
> Any news on my request?

Not yet. It is still in my to-do list. Unfortunately, I need some serious work on the way this app handles notes and checklists. So, probably take more time. Thanks

**Comment by sunilpaulmathew** [comment]
@HarriBuh 
Work in progress
![Screenshot_20230319-133116](https://user-images.githubusercontent.com/15515387/226175384-0f4f9a93-560c-4626-82b8-abc0073a8ef3.jpg)

**Comment by HarriBuh** [comment]
Thanks a lot! Still looking quite confusing, but I guess one can see still chance the design to two and more rows per line, right?

**Comment by sunilpaulmathew** [comment]
> ill looks quite confusing, but I guess one can see still chance the design to two and more rows per line, right?

Yes, you can still change the notes/checklist in a raw. By the way, a checklist will always have black background and white font color + a checklist icon on the bottom left (please see the first item). [Here is a test build](https://www.dropbox.com/s/1ftwechy4ulr8cn/app-fdroid-release.apk?dl=0), if you want to try.
