### ISSUE TITLE
[SUGGESTION] Distinguishing unhidden notes.

### ISSUE THREAD

**Issue by MasterixCZ** [sunilpaulmathew/sNotz#38]
It would be great if there was some way to distinguish hidden notes when I have unhide on. This way I don't know if it is/was a hidden message, and it's also difficult to find when I have a lot of notes. Could show a lock on them for example.
Like this:
![Bez názvu](https://user-images.githubusercontent.com/84620639/220387048-45fd51fe-20bc-4b1f-8a3c-5e1cf1854263.png)

**Comment by sunilpaulmathew** [comment]
@MasterixCZ 
Thank You very much for the suggestion. I'll look into it in future. I have a lot of plans pending for that app. Also, at this moment, long clicking on a note will tell you if it is hidden or not (from the state of switch; please see the attached screenshot).
![Screenshot_20230221-163124](https://user-images.githubusercontent.com/15515387/220388990-a6a8c1f4-04d5-4ffe-87be-68be4211c744.jpg)

By the way, out of curiosity, is the `CZ` in your name has some connection with Czech?

**Comment by MasterixCZ** [comment]
Wow, I wasn't expecting such a quick response! :D And yes, I'm from the Czech Republic and I'm translating sNotz into Czech, it should be all done in a while. :)

**Comment by sunilpaulmathew** [comment]
> Wow, I wasn't expecting such a quick response! :D And yes, I'm from the Czech Republic and I'm translating sNotz into Czech, it should be all done in a while. :)

Thank you. & I'm also living in Czech (Prague) atm. Nice to see someone from Czech here.
