### ISSUE TITLE
Expand/collapse arrow

### ISSUE THREAD

**Issue by FTno** [sunilpaulmathew/sNotz#8]
If my phone is in landscape mode, I noticed that the arrows to expand the notes are missing. There are 2 columns in this mode so if they can't work independently of each other then that explains it. But would it be possible to have an option to always have only 1 column so the arrows are present all the time.
On my phone this is a very minor issue as I nearly always have it in portrait mode, but I have now also installed sNotz on my tablet, and here I always get 2 or more columns and thus never have the expand/collapse arrows.

**Comment by sunilpaulmathew** [comment]
@FTno 
An option to select notes in a number of row is introduced as of commit f97a61deb20b4b8025a9b085aa807cb4eece375b
Setting the number of notes as one will always show expand/collapse button on your tablet. It will be visible on next update (hopefully soon). Closing this issue now. If you are not satisfied, please feel free to reopen this issue.
Thanks

**Comment by FTno** [comment]
Thanks for adding this option, works fine.
